apiVersion: v1
kind: ServiceMonitor
metadata:
  name: pdf-worker-monitor
  namespace: pdf-processing
  labels:
    app: pdf-worker
spec:
  selector:
    matchLabels:
      app: pdf-worker
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-worker-metrics
  namespace: pdf-processing
  labels:
    app: pdf-worker
spec:
  selector:
    app: pdf-worker
  ports:
  - port: 9090
    targetPort: 9090
    name: metrics
  type: ClusterIP
