name: CI

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'setup.py'
      - 'Dockerfile'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'setup.py'
      - 'Dockerfile'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install GTK and WeasyPrint dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpangocairo-1.0-0 \
            libpangoft2-1.0-0 \
            libcairo2 \
            libgdk-pixbuf2.0-0 \
            libffi-dev \
            libxml2 \
            libgdk-pixbuf2.0-dev \
            libgtk-3-0

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          flake8 src tests

      - name: Run tests with pytest
        run: |
          source .venv/bin/activate
          # The tests now cover rolling concurrency, per-page retry, and global Gemini API throttling
          pytest tests/

      - name: Run FastAPI app with uvicorn (smoke test)
        run: |
          source .venv/bin/activate
          nohup uvicorn src.main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl -f http://127.0.0.1:8000/health
          pkill -f uvicorn

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t nest-starters .

      - name: Run Docker container (smoke test)
        run: |
          docker run --rm nest-starters python --version 